openapi: 3.0.0
info:
  title: Learn Express and Swagger.
  description: A course segment for writing docs.
  version: 1.1.0
  contact:
    email: manish@gmail.com
    url: "imvmanish.com"

servers:
  - url: "https://localhost:3000/api/v1"
    description: for local host - secure
  - url: "http://localhost:3000/api/v1"
    description: for local host
